sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
    - example/node_modules

install:
  - npm install
  - cd example
  - npm install

script:
  - npm run lint
  - cd example
  - npm run lint